version: "3.9"

services:
    web:
        container_name: wd07_nginx
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/wd07
            - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - fpm
            - mysql
    fpm:
        container_name: wd07_fpm
        environment:
            PHP_IDE_CONFIG: "serverName=wd07"
        build:
          dockerfile: docker/php/Dockerfile
          context: .
        volumes:
            - ./:/var/www/wd07
        links:
            - mysql
    mysql:
        container_name: wd07_db
        image: mariadb:10.3
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=wd07